# Instructions copied from - https://hub.docker.com/_/python/
#our base image, we chose onbuild to automate some common tasks
FROM python:3-onbuild

# tell the port number the container should expose
EXPOSE 5000

# run the command
CMD ["python", "./app.py"]
