# Use postgres/example user/password credentials
version: '3.1'

services:

  db-docker:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      #PGPORT default: 5432
      PGPORT: 5434
    volumes:
      - ~/Documents/docker/ex-postgres/vols/postgres/data:/var/lib/postgresql/data
    ports:
        #Default for outside:inside is 5432:5432
        - 5433:5434

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
