# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    hostname: db
    domainname: db.com
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGHOST: db
      PGPORT: 5432
    volumes:
      - ~/Documents/docker/ex-postgres/vols/postgres/data:/var/lib/postgresql/data
    ports:
        - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
